name: SHB Backend Node

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:  
      contents: read
      id-token: write
    environment:
      name: 'Production'

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7C2945A7D2244DAD92D3280A8DC6435B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5222F9CE3E47409996FD4F75C652BAFC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B22B571F17A74F4EB8803EFF9B232284 }}

      - name: Set Azure subscription
        run: |
          az account set --subscription ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B22B571F17A74F4EB8803EFF9B232284 }}

      - name: Check if a deployment is in progress for shbbackend
        run: |
          echo "Checking for active deployment process for shbbackend..."
          RESOURCE_GROUP="SHB-Course-Management-System"
          DEPLOYMENT_STATUS=$(az webapp show --name shbbackend --resource-group $RESOURCE_GROUP --query "state" -o tsv)
          
          echo "Current deployment status: $DEPLOYMENT_STATUS"
          
          if [ "$DEPLOYMENT_STATUS" == "Running" ]; then
            echo "Deployment is already in progress for shbbackend. Exiting early."
            echo "::set-output name=deployment_in_progress::true"
          else
            echo "No deployment in progress. Proceeding."
            echo "::set-output name=deployment_in_progress::false"
          fi

      - name: Fetch previous commit (before push)
        run: |
          git fetch origin main --depth=2
          echo "Before push commit:"
          git log --oneline -n 2

      - name: Check for changes in the backend folder
        id: check_changes
        run: |
          git fetch origin main --depth=2
          CHANGES=$(git diff --name-only HEAD~1 HEAD -- backend/)

          if [ -z "$CHANGES" ]; then
            echo "No changes in backend. Skipping build/deploy."
            echo "::set-output name=changes_detected::false"
          else
            echo "Changes found in backend. Proceeding."
            echo "::set-output name=changes_detected::true"
          fi

      - name: Debug changes detected
        #if: ${{ steps.check_changes.outputs.changes_detected == 'true' }}  
        run: 'echo "Changes detected: ${{ steps.check_changes.outputs.changes_detected }}"'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install, Build, and Test (Backend Only)
        run: |
          cd backend
          npm install
          npm run build --if-present

      - name: Zip backend folder for deployment
        run: |
          cd backend
          zip -r ../release.zip .

      - name: Upload deployment artifact
        uses: actions/upload-artifact@v4
        with:
          name: shb-node-app
          path: release.zip

      - name: Deploy to Azure Web App (Linux)
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'shbbackend'
          slot-name: 'Production'
          package: ./release.zip

      - name: Background deploy info
        run: echo "Deployment initiated and will continue in the background."
